### ISSUE TITLE
Does this linux kernel support Freescale imx6q ？

### ISSUE THREAD

**Issue by oPiZiL** [openil/linux#1]
1. Does this linux kernel support Freescale imx6q ？
2. What is the version of linux and xenomai ?

**Comment by vladimiroltean** [comment]
> 1.    Does this linux kernel support Freescale imx6q ？

At the moment there is no explicit support for i.MX devices. The level of support is that of mainline Linux.
As per this [OpenIL mailing list discussion](https://openil.org/ml/listinfo/archives_messages_detail.html?id=83&sortby=thread&mailinglist): "_i.MX6Quad will be supported in OpenIL v1.3 release, which is schedule on 31. August. The platform is i.MX 6Quad SABRE._"

> 2.    What is the version of linux and xenomai ?

Linux kernel version is 4.9.35, [as per Makefile](https://github.com/openil/linux/blob/master/Makefile#L1-L3).
Xenomai version is 3.1-devel, [as per config file](https://github.com/openil/xenomai-3/blob/next/config/version-label).

**Comment by oPiZiL** [comment]
@vladimiroltean   so now this kernel support Freescale imx6q? Is it xenomai patched already?
