### ISSUE TITLE
How to import openil code after modifying linux code

### ISSUE THREAD

**Issue by liu-jeff** [openil/linux#4]
After I modified the Linux kernel code, how do I make the kernel compiled by Openil my modified kernel?

**Comment by vladimiroltean** [comment]
[8.12.6. Using Buildroot during development](https://buildroot.org/downloads/manual/manual.html):
```
export LINUX_OVERRIDE_SRCDIR=/path/to/kernel
make linux-rebuild
make
```

**Comment by liu-jeff** [comment]
> [8.12.6. Using Buildroot during development](https://buildroot.org/downloads/manual/manual.html):
> 
> ```
> export LINUX_OVERRIDE_SRCDIR=/path/to/kernel
> make linux-rebuild
> make
> ```

After modifying the ptp code, how to compile ptp into the kernel, and then compile the kernel embedded in ptp into openil?
